@{
    Offline = @(
        'tests\test-agent-launched.ps1'
        'tests\test-answer-match.ps1'
        'tests\test-auth-backoff.ps1'
        'tests\test-bridge-adapter.ps1'
        'tests\test-choices-form.ps1'
        'tests\test-copilot-activity.ps1'
        'tests\test-daemon-agents.ps1'
        'tests\test-daemon-decisions.ps1'
        'tests\test-daemon-loop.ps1'
        'tests\test-daemon-replies.ps1'
        'tests\test-daemon-sessions.ps1'
        'tests\test-dashboard.ps1'
        'tests\test-decision-args.ps1'
        'tests\test-decision-lifecycle.ps1'
        'tests\test-decision-retry.ps1'
        'tests\test-decision-select-race.ps1'
        'tests\test-detailed-activity.ps1'
        'tests\test-devbox-keepawake.ps1'
        'tests\test-driver-card.ps1'
        'tests\test-hook-functions.ps1'
        'tests\test-hook-spool.ps1'
        'tests\test-hook-stats.ps1'
        'tests\test-hook-status.ps1'
        'tests\test-http-guard.ps1'
        'tests\test-http-session.ps1'
        'tests\test-install-cards.ps1'
        'tests\test-install-clients.ps1'
        'tests\test-install-connection.ps1'
        'tests\test-install-deps.ps1'
        'tests\test-install-http-guard.ps1'
        'tests\test-launch-permissions.ps1'
        'tests\test-launchers.ps1'
        'tests\test-layout-migration.ps1'
        'tests\test-multi-machine.ps1'
        'tests\test-native-hook-install.ps1'
        'tests\test-native-hook.ps1'
        'tests\test-new-session.ps1'
        'tests\test-p3b-contracts.ps1'
        'tests\test-p4-worktree-safety.ps1'
        'tests\test-publication-policy.ps1'
        'tests\test-reliability.ps1'
        'tests\test-reply-card.ps1'
        'tests\test-restart-restore.ps1'
        'tests\test-resume-discovery.ps1'
        'tests\test-resume-sharing.ps1'
        'tests\test-runner.ps1'
        'tests\test-security.ps1'
        'tests\test-state-read.ps1'
        'tests\test-state-snapshot.ps1'
        'tests\test-status-card.ps1'
        'tests\test-stop-session.ps1'
        'tests\test-terminal-window.ps1'
        'tests\test-transcript-cache.ps1'
        'tests\test-turn-end.ps1'
        'tests\test-update.ps1'
        'tests\test-update-outcome.ps1'
        'tests\test-verbose-toggle.ps1'
        'tests\test-worktree-isolation.ps1'
        'tests\test-write-boundary-callers.ps1'
        'tests\test-write-boundary-context.ps1'
        'tests\test-write-boundary-stop.ps1'
        'claude\tests\test-claude-ask-parser.ps1'
        'claude\tests\test-claude-install.ps1'
        'claude\tests\test-claude-transcript.ps1'
        'codex\tests\test-codex.ps1'
    )
    # These execute installers or exercise terminal delivery. Only disposable,
    # GitHub-hosted CI machines may run them; -TargetHome is not an OS sandbox.
    Host = @('tests\test-install-command.ps1')
    Platform = @('tests\test-platform.ps1')
    # Listed for inventory checking, never executed by the offline runner.
    Integration = @(
        'claude\tests\test-claude-integration.ps1'
        'codex\tests\test-codex-integration.ps1'
    )
}
