<#
    Pairing a machine into the fleet: the cryptography and the protocol steps.

    Everything here is pure - no network, no files, no Home Assistant - so every step
    can be driven and checked offline, including a man in the middle. The orchestration
    that moves these messages between machines lives in bridge-pairing-run.ps1.

    See docs/fleet-pairing.md for the design and the threat model. In short: the key
    exchange may cross MQTT, which is not trusted; the code the person types and the
    sponsor's acceptance travel only through a Home Assistant helper, which a client
    holding nothing but broker credentials cannot write.
#>

$script:BridgePairingProtocol = 'agent-ha-bridge pairing v1'
$script:BridgePairingCodeDigits = 6

function ConvertTo-BridgePairingFrame {
    <#
        Joins values for hashing so that no two different lists can produce the same
        bytes: each value is preceded by its length. Joining with a separator is not
        enough here, because the inputs include machine names and base64 that a
        separator could appear in, and a transcript that two different exchanges could
        share is exactly the collision the commitment exists to prevent.
    #>
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Values)

    $stream = [IO.MemoryStream]::new()
    try {
        foreach ($value in $Values) {
            # Assigned in two statements rather than from an if expression: an if
            # expression unrolls its result, so a one-byte value arrived as a bare
            # [byte] and an empty one as $null, and a one-letter machine name could
            # not be hashed at all.
            [byte[]]$bytes = [Text.Encoding]::UTF8.GetBytes([string]$value)
            if ($value -is [byte[]]) { [byte[]]$bytes = $value }
            $length = [BitConverter]::GetBytes([uint32]$bytes.Length)
            if ([BitConverter]::IsLittleEndian) { [Array]::Reverse($length) }
            $stream.Write($length, 0, 4)
            $stream.Write($bytes, 0, $bytes.Length)
        }
        , $stream.ToArray()
    }
    finally { $stream.Dispose() }
}

function Get-BridgePairingHash {
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Values)
    , [Security.Cryptography.SHA256]::HashData((ConvertTo-BridgePairingFrame -Values $Values))
}

function ConvertTo-BridgePairingHex {
    param([Parameter(Mandatory)][byte[]]$Bytes)
    [Convert]::ToHexString($Bytes).ToLowerInvariant()
}

function New-BridgePairingId {
    <# A random 16-byte identifier as hex: an attempt id, or a fleet id. Not a secret. #>
    ConvertTo-BridgePairingHex -Bytes ([Security.Cryptography.RandomNumberGenerator]::GetBytes(16))
}

function New-BridgePairingNonce {
    [Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))
}

function New-BridgeFleetSecret {
    <# 32 random bytes, base64 - the same shape #77 generated by hand. #>
    [Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))
}

function New-BridgePairingKeyPair {
    <#
        An ephemeral P-256 key for one attempt. The caller disposes of it when the
        attempt ends, whatever the outcome; nothing here keeps it.
    #>
    $key = [Security.Cryptography.ECDiffieHellman]::Create([Security.Cryptography.ECCurve+NamedCurves]::nistP256)
    [pscustomobject]@{
        Key    = $key
        Public = [Convert]::ToBase64String($key.ExportSubjectPublicKeyInfo())
    }
}

function Import-BridgePairingPublicKey {
    <#
        A peer's public key, refused unless it is exactly a P-256 key. Accepting any
        curve the peer names would let a man in the middle steer both ends onto a weak
        one.
    #>
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Public)

    $bytes = $null
    try { $bytes = [Convert]::FromBase64String($Public) } catch { throw 'the peer''s public key is not base64' }
    $peer = [Security.Cryptography.ECDiffieHellman]::Create()
    try {
        $read = 0
        $peer.ImportSubjectPublicKeyInfo($bytes, [ref]$read)
        if ($read -ne $bytes.Length) { throw 'trailing bytes' }
        $curve = $peer.ExportParameters($false).Curve
        $isP256 = $curve.IsNamed -and (
            $curve.Oid.Value -eq '1.2.840.10045.3.1.7' -or $curve.Oid.FriendlyName -in @('nistP256', 'ECDSA_P256'))
        if (-not $isP256) { throw 'not P-256' }
        $peer
    }
    catch {
        $peer.Dispose()
        throw "the peer's public key was refused: $($_.Exception.Message)"
    }
}

function Get-BridgePairingCommit {
    <# What the joiner commits to before it has seen the sponsor's key. #>
    param(
        [Parameter(Mandatory)][string]$Public,
        [Parameter(Mandatory)][string]$Nonce
    )
    ConvertTo-BridgePairingHex -Bytes (Get-BridgePairingHash -Values @('commit', $Public, $Nonce))
}

function Get-BridgePairingTranscript {
    <#
        Everything both ends agreed on, as one hash. The code, the key and the
        acceptance are all derived from it, so a man in the middle - who necessarily
        runs two exchanges with two different transcripts - gets a different code, a
        different key and a different acceptance on each side.
    #>
    param(
        [Parameter(Mandatory)][string]$Attempt,
        [Parameter(Mandatory)][string]$FleetId,
        [Parameter(Mandatory)][string]$Joiner,
        [Parameter(Mandatory)][string]$Sponsor,
        [Parameter(Mandatory)][string]$JoinerPublic,
        [Parameter(Mandatory)][string]$SponsorPublic,
        [Parameter(Mandatory)][string]$JoinerNonce,
        [Parameter(Mandatory)][string]$SponsorNonce
    )
    , (Get-BridgePairingHash -Values @(
            $script:BridgePairingProtocol, $Attempt, $FleetId, $Joiner, $Sponsor,
            $JoinerPublic, $SponsorPublic, $JoinerNonce, $SponsorNonce))
}

function Get-BridgePairingCode {
    <#
        The six digits the person carries from the joiner's screen into Home
        Assistant. Not a secret - it is only compared - so it is derived from the
        transcript alone.
    #>
    param([Parameter(Mandatory)][byte[]]$Transcript)

    $hash = Get-BridgePairingHash -Values @('code', $Transcript)
    $value = ([uint32]$hash[0] -shl 24) -bor ([uint32]$hash[1] -shl 16) -bor ([uint32]$hash[2] -shl 8) -bor [uint32]$hash[3]
    $modulus = [uint32][Math]::Pow(10, $script:BridgePairingCodeDigits)
    ([uint32]($value % $modulus)).ToString().PadLeft($script:BridgePairingCodeDigits, '0')
}

function ConvertTo-BridgePairingTypedCode {
    <# What the person typed, as bare digits: spaces and dashes are how people group them. #>
    param([AllowNull()][AllowEmptyString()][string]$Typed)
    ([string]$Typed) -replace '[\s\-]', ''
}

function Test-BridgePairingEqual {
    <# A fixed-time comparison, for codes and acceptances. #>
    param(
        [AllowNull()][AllowEmptyString()][string]$A,
        [AllowNull()][AllowEmptyString()][string]$B
    )
    if ([string]::IsNullOrEmpty($A) -or [string]::IsNullOrEmpty($B)) { return $false }
    [Security.Cryptography.CryptographicOperations]::FixedTimeEquals(
        [Text.Encoding]::UTF8.GetBytes($A), [Text.Encoding]::UTF8.GetBytes($B))
}

function Get-BridgePairingAcceptance {
    <#
        What the sponsor writes into the Home Assistant helper once the code matches.
        The joiner accepts a secret only alongside this, bound to its own transcript:
        without it, an attacker could complete a separate exchange with the joiner,
        hand it a secret the attacker knows, and then ask it for sessions.
    #>
    param(
        [Parameter(Mandatory)][byte[]]$Transcript,
        [Parameter(Mandatory)][string]$Joiner
    )
    $tag = (ConvertTo-BridgePairingHex -Bytes (Get-BridgePairingHash -Values @('accept', $Transcript))).Substring(0, 16)
    "accepted:${Joiner}:$tag"
}

function Get-BridgePairingSessionKey {
    <# The AES key for this attempt: ECDH, then HKDF salted with the transcript. #>
    param(
        [Parameter(Mandatory)][Security.Cryptography.ECDiffieHellman]$Key,
        [Parameter(Mandatory)][string]$PeerPublic,
        [Parameter(Mandatory)][byte[]]$Transcript
    )
    $peer = Import-BridgePairingPublicKey -Public $PeerPublic
    try {
        $shared = $Key.DeriveKeyFromHash($peer.PublicKey, [Security.Cryptography.HashAlgorithmName]::SHA256)
        try {
            , [Security.Cryptography.HKDF]::DeriveKey([Security.Cryptography.HashAlgorithmName]::SHA256,
                $shared, 32, $Transcript, [Text.Encoding]::UTF8.GetBytes('fleet secret'))
        }
        finally { [Security.Cryptography.CryptographicOperations]::ZeroMemory($shared) }
    }
    finally { $peer.Dispose() }
}

function Protect-BridgePairingSecret {
    <# AES-256-GCM, with the transcript as associated data. Returns nonce ‖ ciphertext ‖ tag as base64. #>
    param(
        [Parameter(Mandatory)][byte[]]$SessionKey,
        [Parameter(Mandatory)][string]$Secret,
        [Parameter(Mandatory)][byte[]]$Transcript
    )
    $plain = [Text.Encoding]::UTF8.GetBytes($Secret)
    $nonce = [Security.Cryptography.RandomNumberGenerator]::GetBytes(12)
    $cipher = [byte[]]::new($plain.Length)
    $tag = [byte[]]::new(16)
    $aes = [Security.Cryptography.AesGcm]::new($SessionKey, 16)
    try { $aes.Encrypt($nonce, $plain, $cipher, $tag, $Transcript) }
    finally {
        $aes.Dispose()
        [Security.Cryptography.CryptographicOperations]::ZeroMemory($plain)
    }
    [Convert]::ToBase64String([byte[]]($nonce + $cipher + $tag))
}

function Unprotect-BridgePairingSecret {
    <# The secret, or a throw if the ciphertext was altered or was made for a different transcript. #>
    param(
        [Parameter(Mandatory)][byte[]]$SessionKey,
        [Parameter(Mandatory)][string]$Ciphertext,
        [Parameter(Mandatory)][byte[]]$Transcript
    )
    $blob = $null
    try { $blob = [Convert]::FromBase64String($Ciphertext) } catch { throw 'the secret message is not base64' }
    if ($blob.Length -lt (12 + 16 + 1)) { throw 'the secret message is too short' }
    $nonce = [byte[]]$blob[0..11]
    $tag = [byte[]]$blob[($blob.Length - 16)..($blob.Length - 1)]
    $cipher = [byte[]]$blob[12..($blob.Length - 17)]
    $plain = [byte[]]::new($cipher.Length)
    $aes = [Security.Cryptography.AesGcm]::new($SessionKey, 16)
    try {
        try { $aes.Decrypt($nonce, $cipher, $tag, $plain, $Transcript) }
        catch { throw 'the secret message did not authenticate' }
        [Text.Encoding]::UTF8.GetString($plain)
    }
    finally {
        $aes.Dispose()
        [Security.Cryptography.CryptographicOperations]::ZeroMemory($plain)
    }
}

# ------------------------------------------------------------------------- messages
# Every message names the protocol, its type and its attempt, and is checked for all
# three before anything in it is used. A message for another attempt, or of the wrong
# type at this step, is refused rather than skipped past: on an untrusted transport
# the only safe reading of "unexpected" is "not for us".

function New-BridgePairingMessage {
    param([Parameter(Mandatory)][string]$Type, [Parameter(Mandatory)][string]$Attempt, [hashtable]$Fields = @{})
    $message = [ordered]@{ protocol = $script:BridgePairingProtocol; type = $Type; attempt = $Attempt }
    foreach ($k in $Fields.Keys) { $message[$k] = $Fields[$k] }
    [pscustomobject]$message
}

function Assert-BridgePairingMessage {
    param(
        [AllowNull()]$Message,
        [Parameter(Mandatory)][string]$Type,
        [Parameter(Mandatory)][string]$Attempt,
        [string[]]$Fields = @()
    )
    if ($null -eq $Message) { throw "expected a $Type message, got nothing" }
    foreach ($name in @('protocol', 'type', 'attempt') + $Fields) {
        if (-not $Message.PSObject.Properties[$name] -or [string]::IsNullOrEmpty([string]$Message.$name)) {
            throw "the $Type message has no $name"
        }
    }
    if ([string]$Message.protocol -cne $script:BridgePairingProtocol) { throw "unsupported pairing protocol '$($Message.protocol)'" }
    if ([string]$Message.type -cne $Type) { throw "expected a $Type message, got '$($Message.type)'" }
    if ([string]$Message.attempt -cne $Attempt) { throw "the $Type message belongs to another attempt" }
}

# ------------------------------------------------------------------- the helper's text
# One Home Assistant helper carries every step a person or the request touches, because
# it is the one channel a broker-only client cannot write:
#   request:<sponsor slug>:<attempt>:<fleet id>:<joiner>:<commit>   written by the joiner
#   <six digits>                                                   typed by the person
#   accepted:<joiner>:<tag> / refused:<joiner>                      written by the sponsor

function ConvertTo-BridgePairingRequest {
    param(
        [Parameter(Mandatory)][string]$SponsorSlug,
        [Parameter(Mandatory)][string]$Attempt,
        [Parameter(Mandatory)][string]$FleetId,
        [Parameter(Mandatory)][string]$Joiner,
        [Parameter(Mandatory)][string]$Commit
    )
    foreach ($part in @($SponsorSlug, $Attempt, $FleetId, $Joiner, $Commit)) {
        if ($part.Contains(':')) { throw 'a pairing request field cannot contain a colon' }
    }
    "request:${SponsorSlug}:${Attempt}:${FleetId}:${Joiner}:${Commit}"
}

function ConvertFrom-BridgePairingRequest {
    <# The request in the helper, or $null when it holds something else. #>
    param([AllowNull()][AllowEmptyString()][string]$Value)
    if ([string]$Value -notmatch '^request:([a-z0-9_]+):([0-9a-f]{32}):([0-9a-f]{32}):([^:]+):([0-9a-f]{64})$') { return $null }
    [pscustomobject]@{ SponsorSlug = $Matches[1]; Attempt = $Matches[2]; FleetId = $Matches[3]; Joiner = $Matches[4]; Commit = $Matches[5] }
}

# ---------------------------------------------------------------------- the joiner

function New-BridgePairingJoiner {
    <# Starts an attempt. Returns the state and the request to write into the helper. #>
    param(
        [Parameter(Mandatory)][string]$FleetId,
        [Parameter(Mandatory)][string]$Joiner,
        [Parameter(Mandatory)][string]$Sponsor,
        [Parameter(Mandatory)][string]$SponsorSlug
    )
    $pair = New-BridgePairingKeyPair
    $nonce = New-BridgePairingNonce
    $attempt = New-BridgePairingId
    $commit = Get-BridgePairingCommit -Public $pair.Public -Nonce $nonce
    [pscustomobject]@{
        Role = 'joiner'; Phase = 'committed'
        Attempt = $attempt; FleetId = $FleetId; Joiner = $Joiner; Sponsor = $Sponsor
        Key = $pair.Key; Public = $pair.Public; Nonce = $nonce
        Transcript = $null; Code = ''; SessionKey = $null
        Request = ConvertTo-BridgePairingRequest -SponsorSlug $SponsorSlug -Attempt $attempt `
            -FleetId $FleetId -Joiner $Joiner -Commit $commit
    }
}

function Receive-BridgePairingOffer {
    <# Takes the sponsor's offer; returns the reveal to publish. The code is then on the state. #>
    param([Parameter(Mandatory)]$State, [AllowNull()]$Message)
    if ($State.Phase -cne 'committed') { throw "an offer is not expected while $($State.Phase)" }
    Assert-BridgePairingMessage -Message $Message -Type 'offer' -Attempt $State.Attempt -Fields @('public', 'nonce', 'sponsor')
    if ([string]$Message.sponsor -cne $State.Sponsor) { throw "the offer came from '$($Message.sponsor)', not $($State.Sponsor)" }
    $State.Transcript = Get-BridgePairingTranscript -Attempt $State.Attempt -FleetId $State.FleetId `
        -Joiner $State.Joiner -Sponsor $State.Sponsor -JoinerPublic $State.Public -SponsorPublic ([string]$Message.public) `
        -JoinerNonce $State.Nonce -SponsorNonce ([string]$Message.nonce)
    $State.SessionKey = Get-BridgePairingSessionKey -Key $State.Key -PeerPublic ([string]$Message.public) -Transcript $State.Transcript
    $State.Code = Get-BridgePairingCode -Transcript $State.Transcript
    $State.Phase = 'revealed'
    New-BridgePairingMessage -Type 'reveal' -Attempt $State.Attempt -Fields @{ public = $State.Public; nonce = $State.Nonce }
}

function Complete-BridgePairingJoin {
    <#
        The secret, given what the helper now says and the sponsor's secret message.
        Throws unless the helper holds the acceptance for this joiner's own transcript.
    #>
    param([Parameter(Mandatory)]$State, [AllowNull()][AllowEmptyString()][string]$HelperValue, [AllowNull()]$Message)
    if ($State.Phase -cne 'revealed') { throw "the join cannot complete while $($State.Phase)" }
    if ([string]$HelperValue -ceq "refused:$($State.Joiner)") { throw "$($State.Sponsor) refused the code" }
    $expected = Get-BridgePairingAcceptance -Transcript $State.Transcript -Joiner $State.Joiner
    if (-not (Test-BridgePairingEqual -A ([string]$HelperValue) -B $expected)) {
        throw "Home Assistant does not show $($State.Sponsor) accepting this exchange"
    }
    Assert-BridgePairingMessage -Message $Message -Type 'secret' -Attempt $State.Attempt -Fields @('ciphertext')
    $secret = Unprotect-BridgePairingSecret -SessionKey $State.SessionKey -Ciphertext ([string]$Message.ciphertext) -Transcript $State.Transcript
    $State.Phase = 'joined'
    $secret
}

# --------------------------------------------------------------------- the sponsor

function New-BridgePairingSponsor {
    <# Takes a request from the helper; returns the state and the offer to publish. #>
    param(
        [Parameter(Mandatory)]$Request,
        [Parameter(Mandatory)][string]$FleetId,
        [Parameter(Mandatory)][string]$Sponsor,
        [Parameter(Mandatory)][string]$SponsorSlug
    )
    if ([string]$Request.SponsorSlug -cne $SponsorSlug) { throw 'the request is for another machine' }
    if ([string]$Request.FleetId -cne $FleetId) { throw 'the request is for another fleet' }
    $pair = New-BridgePairingKeyPair
    $nonce = New-BridgePairingNonce
    $state = [pscustomobject]@{
        Role = 'sponsor'; Phase = 'offered'
        Attempt = [string]$Request.Attempt; FleetId = $FleetId; Joiner = [string]$Request.Joiner; Sponsor = $Sponsor
        Commit = [string]$Request.Commit; Key = $pair.Key; Public = $pair.Public; Nonce = $nonce
        Transcript = $null; Code = ''; SessionKey = $null
    }
    [pscustomobject]@{
        State = $state
        Offer = New-BridgePairingMessage -Type 'offer' -Attempt $state.Attempt -Fields @{ public = $pair.Public; nonce = $nonce; sponsor = $Sponsor }
    }
}

function Receive-BridgePairingReveal {
    <# Takes the joiner's reveal and checks it against the commitment. The code is then on the state. #>
    param([Parameter(Mandatory)]$State, [AllowNull()]$Message)
    if ($State.Phase -cne 'offered') { throw "a reveal is not expected while $($State.Phase)" }
    Assert-BridgePairingMessage -Message $Message -Type 'reveal' -Attempt $State.Attempt -Fields @('public', 'nonce')
    $commit = Get-BridgePairingCommit -Public ([string]$Message.public) -Nonce ([string]$Message.nonce)
    if (-not (Test-BridgePairingEqual -A $commit -B $State.Commit)) { throw 'the reveal does not match the commitment' }
    $State.Transcript = Get-BridgePairingTranscript -Attempt $State.Attempt -FleetId $State.FleetId `
        -Joiner $State.Joiner -Sponsor $State.Sponsor -JoinerPublic ([string]$Message.public) -SponsorPublic $State.Public `
        -JoinerNonce ([string]$Message.nonce) -SponsorNonce $State.Nonce
    $State.SessionKey = Get-BridgePairingSessionKey -Key $State.Key -PeerPublic ([string]$Message.public) -Transcript $State.Transcript
    $State.Code = Get-BridgePairingCode -Transcript $State.Transcript
    $State.Phase = 'awaiting-code'
}

function Resolve-BridgePairingCode {
    <#
        Judges what the person typed. Returns { Accepted; Helper; Message }: the text to
        write into the helper, and - only when the code matched - the secret message.
    #>
    param([Parameter(Mandatory)]$State, [AllowNull()][AllowEmptyString()][string]$Typed, [Parameter(Mandatory)][string]$Secret)
    if ($State.Phase -cne 'awaiting-code') { throw "a code is not expected while $($State.Phase)" }
    $digits = ConvertTo-BridgePairingTypedCode -Typed $Typed
    if (-not (Test-BridgePairingEqual -A $digits -B $State.Code)) {
        $State.Phase = 'refused'
        return [pscustomobject]@{ Accepted = $false; Helper = "refused:$($State.Joiner)"; Message = $null }
    }
    $State.Phase = 'accepted'
    [pscustomobject]@{
        Accepted = $true
        Helper = Get-BridgePairingAcceptance -Transcript $State.Transcript -Joiner $State.Joiner
        Message = New-BridgePairingMessage -Type 'secret' -Attempt $State.Attempt -Fields @{
            ciphertext = Protect-BridgePairingSecret -SessionKey $State.SessionKey -Secret $Secret -Transcript $State.Transcript
        }
    }
}

function Close-BridgePairingState {
    <# Disposes of the ephemeral key and wipes the session key, whatever the outcome. #>
    param([AllowNull()]$State)
    if ($null -eq $State) { return }
    if ($State.Key) { $State.Key.Dispose(); $State.Key = $null }
    if ($State.SessionKey) { [Security.Cryptography.CryptographicOperations]::ZeroMemory($State.SessionKey); $State.SessionKey = $null }
}
